openapi: '3.0.3'
info:
  title: API Bibliotheque HEI
  version: '1.0'
  description: Gestion des livres et des emprunts
servers:
  - url: https://api.hei.school/v1
  - url: https://staging.hei.school/v1
paths:
  /livres/{id}:
    get:
      summary: 'lire un livres'
      parameters:
        - name: id
          in: path
          required: true
          description: L'identifiant unique du livre
          schema:
            type: integer
      responses:
        '200':
          description: OK
        '404':
          description: Livre introuvable
