openapi: 3.0.3
info:
  title: API Bibliotheque HEI
  version: '1.0'
  description: Gestion des livres et des emprunts
servers:
  - url: https://api.hei.school/v1
  - url: https://staging.hei.school/v1
paths:
  /livres:
    post:
      summary: 'Ajouter un livre'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                titre:
                  type: string
                  description: Le titre du livre
                auteur:
                  type: string
                  description: L'auteur du livre
              required:
                - titre
      responses:
        '201':
          description: Livre créé
        '422':
          description: Requête invalide
