openapi: 3.0.3
info:
  title: 'API Cours HEI'
  version: 1.0.1
  description: "Application de gestion de cours"
servers:
  - url: 'https://api.hei.school/v1'
paths:
  /cours:
    get:
      summary: Récuperer la liste des cours
      parameters:
        - in: query
          name: id
          description: "Identifiant du cour"
          schema:
            type: integer
            default: 1
          required: false
        - in: query
          name: UE
          description: "L'unité d'enseignement"
          schema:
            type: string
            enum: ["WEB1", "WEB2","WEB3", "API", "POO", "PROG1", "SYS1"]
          required: true
        - in: query
          name: duration
          description: "La durée d'un cour"
          schema:
            type: string
            format: date
          required: false
      responses:
        '200':
          description: 'Cours trouvés'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cour'
        '422':
          description: "UE invalide"
    post:
      summary: "Création d'un cour"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Cour"
        responses:
          '201':
            description: "Cours créé avec succès"
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Cour'
          '422':
            description: "Arguments invalide"


components:content:
              application/json:
                schema:
                  type array
  schemas:
    Cour:
      type: object
      properties:
        UE:
          type: string
          enum: ["WEB1", "WEB2","WEB3", "API", "POO", "PROG1", "SYS1"]
        enseignant:
          type: object
        groupe:
          type: object
        volumeHorraire:
          type: string
          format: date
        dateDeDebut:
          type: string
          format: date
        dateDeFin:
          type: string
          format: date

    CourWithoutId:
      type: object
    Erreur:
      type: object
      properties:
        status:
          type: integer
          example: 404
        type:
          type: string
          example: "https://example.com/not-found"
        title:
          type: string
          example: "Cour introuvable"
        detail:
          type: string
          example: "Livre introuvable dans le chemin spéciié"

