openapi: 3.0.3
info:
  title: "API Cours HEI"
  version: 1.0.0
servers:
  - url: "https://api.hei.school/v1"
paths:
  /cours:
    get:
      summary: Récupérer la liste des cours
      responses:
        "200":
          description: "Cours trouvés"
    post:
      summary: Créer des cours
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
      responses:
        "201":
          description: "Cours créés avec succès"
        "422":
          description: "Données invalides"
  /cours/{id}:
    get:
      summary: Récupérer un cours par son identifiant
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "Cours trouvé"
        "404":
          description: "Cours non trouvé"
    put:
      summary: Mettre à jour un cours par son identifiant
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "Cours mis à jour avec succès"
        "404":
          description: "Cours introuvable"
        "422":
          description: "Données invalides"
    delete:
      summary: Supprimer un cours par son identifiant
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: "Cours supprimé avec succès"
        "404":
          description: "Cours introuvable"
