openapi: 3.0.3
info:
  title: "API Cours HEI"
  version: 1.0.0
servers:
  - url: "https://api.hei.school/v1"
paths:
  /cours:
    get:
      tags:
        - Cours
      summary: Récupérer la liste des cours
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
      responses:
        "200":
          description: "Cours trouvés"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Cours"
    post:
      tags:
        - Cours
      summary: Créer des cours
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Cours"
      responses:
        "201":
          description: "Cours créés avec succès"
        "422":
          description: "Données invalides"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Erreur"
  /cours/{id}:
    get:
      tags:
        - Cours
      summary: Récupérer un cours par son identifiant
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "Cours trouvé"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cours"
        "404":
          description: "Cours non trouvé"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Erreur"
    put:
      tags:
        - Cours
      summary: Mettre à jour un cours par son identifiant
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Cours"
      responses:
        "200":
          description: "Cours mis à jour avec succès"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cours"
        "404":
          description: "Cours introuvable"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Erreur"
        "422":
          description: "Données invalides"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Erreur"
    delete:
      tags:
        - Cours
      summary: Supprimer un cours par son identifiant
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: "Cours supprimé avec succès"
        "404":
          description: "Cours introuvable"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Erreur"
components:
  schemas:
    Cours:
      type: object
      properties:
        id:
          type: integer
          example: 1
        code:
          type: string
          example: "PROG1"
        intitule:
          type: string
          example: "Algorithmique et la programmation en JavaScript"
        credits:
          type: integer
          example: 6
          required:
            - code
            - intitule
    Erreur:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
tags:
  - name: Cours
    description: Opérations liées au Cours
security:
  - bearerAuth: []
