openapi: 3.0.3
info:
  title: API Bibliothèque HEI
  version: 1.0.0
  description: Gestion des livres et des emprunts
servers:
  - url: 'https://api.hei.school/v1'
  - url: 'https://staging.hei.school/v1'
    description: Environnement de test
paths: { }